* <2023-06-08 Thu>

** Intro
I'm taking my first steps to formalize study materils for the Extra Class license! I have a number of study materials, but so far my efforts have been all over the place and not focused.
*** Gordon West's Extra Class Book
*** Extra Exam Prep iPhone App
*** ARRL Extra License Manual

My plan is to go in depth in this document into topics that I'm struggling with and questions that I got wrong in practice tests. 

Talking to Scott yesterday, he was telling me that his method was 15 minutes in the morning, 15 minutes at night of studying.

** E2A
Note from GW book: 100% on 2/28!

** E2E
*** Highlighted in the back of the GW book
2E08
2E09
2E10
2E12

** Reviewing Questions from Screenshots
*** 3A03 - 70
A. When the moon is at perigree
When the moon is at perigree and must appearing above the horizon, that is the PERfect time.
*** 3A05 - 56
C. Warm and Cold Fronts
They form large-surface reflectors for VHF and microwave signals

*** 3A06 - 46
B. Switch to a lower frequency HF Band
When the upper HF bands close in the evening, switch to the next lower band. 

*** 3A11 - 57
B. 100 to 300 miles
Because the troposphere is lower than the ionosphere, skip distances are less.

*** 3A13 - 55
A. CW
It's already hard, so this mode provides the best opportunity. Receiver may not even hear a tone, only short and long rushes of superimposed noise.

* <2023-06-10 Sat>
** More questions from screenshots
*** 3A14 - 44 -> :research_in_manual:
B. Waves with a rotating electric field
Used for satellite contacts because circular polarizated antennas have a rotating electric field. 

*** 3B02 - 48
C. About 5000 miles for transequatorial propagation.
Stations mus be equidistant from the geomagnetic equator. Reflections occur in and off the F2 layers during times of high sunspot activity.
*** 2E04 - 86
A. Selective fading has occurred.
Propogation is causing the digital signal to fade in out. 

*** 2E10 - 88
C. PSK31
Uses sinusoidal data pulses and efficient varicode characters for low bandwidth

*** 2E13 - 84
D. 300 baud packet
On the worldwide bands, faster than other modes.

*** 3B04 - 43 ->                                         :research_in_manual:
B. Independent waves, generated in the ionosophere that are elliptically polarized
2 waves, clockwise and counterclockwise with different paths

*** 3B07 - 43 ->                                         :research_in_manual:
C. They become elliptically polarized


*** 3B10 - 47


*** 3B12 - 47
*** 3C03 - 49
*** 3C04 - 49
*** 3C05 - 49
*** 3C07 - 50
*** 3C09 - 51
*** 3C10 - 52
*** 3C11 - 45
*** 3C12 - 58
*** 3C14 - 55
*** 4A02 - 205
*** 4A04 - 208
*** 4A05 - 194
*** 4A06 - 208
*** 4A07 - 243
*** 4A09 - 208
*** 4B02 - 206
*** 4B03 - 210
*** 4B04 - 210
*** 4B05 - 210
*** 4B07 - 210
*** 4B08 - 209
*** 4B09 - 209
*** 4B10 - 206
